### ISSUE TITLE
Add output for URL base

### ISSUE THREAD

**Issue by QuintinWillison** [ably/sdk-upload-action#32]
This is to support workflows that need to run a tool that generates static website content, where that static website content needs to embed the base URL.

An example is [gopages](https://github.com/JohnStarich/go)' [`--base` argument](https://johnstarich.com/go/gopages/pkg/github.com/johnstarich/go/gopages/) (see [this internal Slack comment](https://ably-real-time.slack.com/archives/C0114KK7S6R/p1623926815099500?thread_ts=1623922381.097100&cid=C0114KK7S6R) from @lmars, leading to https://github.com/ably/ably-go/issues/346).

The idea is that we would use this action twice in any given workflow that needs this information up front. Something like:

```yaml
steps:
  - uses: ably/sdk-upload-action@v1
    id: sdk-upload-prempt
    with:
      mode: preempt
      artifactName: docs

  - name: Build Documentation
    env:
      BASE_URL: ${{ steps.sdk-upload-prempt.outputs.baseUrl }}
    run: someDocsBuildTool "$BASE_URL"

  - uses: ably/sdk-upload-action@v1
    with:
      s3AccessKeyId: ${{ secrets.SDK_S3_ACCESS_KEY_ID }}
      s3AccessKey: ${{ secrets.SDK_S3_ACCESS_KEY }}
      sourcePath: some/docs/build/path
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      artifactName: docs
```

Where the `baseUrl` action step's output value (`BASE_URL` env injected into the subsequent step) would be the absolute `https` address to the folder to which the SDK Upload Action will upload... being the same URL that is supplied to GitHub's deployment API within the action's implementation, so we get a nice 'View deployment' button in PRs - for example, [this Flutter PR's button](https://github.com/ably/ably-flutter/pull/305#event-5942174346) which links to this output:

`https://sdk.ably.com/builds/ably/ably-flutter/pull/307/dartdoc/`

Formulated by combining `bucketName` and `keyPrefix`, in the current implementation, [here](https://github.com/ably/sdk-upload-action/blob/51789744a865585f887a922995b7166dfb93ca4f/src/index.ts#L135).
